### ISSUE TITLE
How to change password?

### ISSUE THREAD

**Issue by Xc1Ym** [isaudits/docker-beef#1]
How to change password?
When I use `docker run` to change password

**Comment by mcjon3z** [comment]
Sorry I never fleshed out the readme on this one. 

Various settings can be changed through environment variables. You can see the full list inside the dockerfile. Use the -e flag to pass values for BEEF_USER and BEEF_PASSWORD to set them as you wish.

**Comment by Xc1Ym** [comment]
> Sorry I never fleshed out the readme on this one.
> 
> Various settings can be changed through environment variables. You can see the full list inside the dockerfile. Use the -e flag to pass values for BEEF_USER and BEEF_PASSWORD to set them as you wish.

thank you
